name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: powershell
        run: |
          python -m venv venv
          & venv\Scripts\Activate
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt } else { Write-Host "No requirements.txt found, skipping dependencies installation." }


      - name: Run Selenium test
        shell: powershell
        run: |
          & venv\Scripts\Activate
          python tests/test_login.py
