name: CI/CD Pipeline

on: 
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get Chrome Version
        id: chrome_version
        run: echo "VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)" >> $GITHUB_ENV

      - name: Install Matching ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${{ env.VERSION }}/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver



      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Tests
        run: python test_app.py
